version: '2'
services:
    home-app:
        image: home
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://home-postgresql:5432/home
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    home-postgresql:
        extends:
            file: postgresql.yml
            service: home-postgresql
